version: '3'

services:
  scripts:
    container_name: rabbitmq_scripts
    build: .
    volumes:
      - ./src:/usr/src/scripts/
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=postnl 
      - RABBITMQ_DEFAULT_PASS=postnl
      - RABBITMQ_DEFAULT_VHOST=postnl